version: "3.8"

services:
  backend:
    image: amitahir/jobhubnow:backend
    container_name: jobhubnow-backend
    restart: always
    ports:
      - "5001:5000"
    env_file:
      - ./Backend/.env

  frontend:
    image: amitahir/jobhubnow:frontend
    container_name: jobhubnow-frontend
    restart: always
    ports:
      - "3001:80"