version: "3.8"

services:
  backend:
    image: amitahir/jobhubnow:backend-${TAG}
    restart: always
    ports:
      - "5001:5000"
    env_file:
      - ./Backend/.env

  frontend:
    image: amitahir/jobhubnow:frontend-${TAG}
    restart: always
    ports:
      - "3001:80"