name: Deploy to EC2

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Backend install
      - name: Install backend dependencies
        working-directory: Backend
        run: npm ci

      - name: Build backend
        working-directory: Backend
        run: npm run build

      # Frontend install
      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      # Package files
      - name: Create deployment package
        run: |
          mkdir deploy

          # backend
          cp -r Backend/dist deploy/
          cp Backend/package*.json deploy/
          cp Backend/ecosystem.config.cjs deploy/

          # frontend build
          cp -r frontend/dist deploy/frontend

          tar -czf deploy.tar.gz -C deploy .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: deployment-package
          path: deploy.tar.gz


  deploy:
    name: Deploy to EC2
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: deployment-package

      - name: Deploy via SSH
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}

        run: |
          echo "$SSH_PRIVATE_KEY" > key.pem
          chmod 600 key.pem

          scp -i key.pem -o StrictHostKeyChecking=no deploy.tar.gz $EC2_USERNAME@$EC2_HOST:/tmp/

          ssh -i key.pem -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_HOST << 'EOF'

            cd /var/www/job-portal

            tar -xzf /tmp/deploy.tar.gz
            rm /tmp/deploy.tar.gz

            npm ci --omit=dev

            if pm2 describe job-portal > /dev/null 2>&1; then
              pm2 reload ecosystem.config.cjs
            else
              pm2 start ecosystem.config.cjs
            fi

            pm2 save

          EOF

          rm key.pem